markdown: kramdown

permalink: /articles/:categories/:title/
sections:
- key: gravit
  icon: icon_gravit
  title: Gravit
  pages:
  - key: index
    title: Overview
- key: company
  icon: icon_quasado
  title: Company
  pages:
  - key: index
    title: About us
  - key: contact
    title: Contact